### PR TITLE
Add time at end of secondary on (almost) all modes

### PR DESCRIPTION
**Pull request by jasonm23**
- Provide a customizable format for icon spacing `lambda-line-time-icon-format`
- I added a version bump to 0.2.0 as the package is still at 0.1

### CODE REVIEW

**Comment by jasonm23** [comment]
Prog Mode

Screenshot 2022-09-17 at 7 42 56 PM

Dired

Screenshot 2022-09-17 at 7 40 41 PM

iBuffer

Screenshot 2022-09-17 at 7 41 10 PM

Magit status

Screenshot 2022-09-17 at 7 40 33 PM

- - - 

Need to understand why this is happening on Magit Log view...

Screenshot 2022-09-17 at 7 44 53 PM

**Comment by jasonm23** [comment]
Looks like it does this without the clock though...

Screenshot 2022-09-17 at 7 47 51 PM

**Comment by jasonm23** [comment]
Definitely more I can do, but I feel this is ready to go. Do let me know if I can improve anything.

FYI, I'm building a dedicated clock font, with 144 Glyphs to show the nearest 5 mins (i.e. 12x12) on a 12hr clock face.  The simplicity of using a font has already proven stable, and with a custom font, I can add a few alternate styles easily.

I did try using an animated SVG clock, but after running it overnight it crashed Emacs.  At a guess, either the SVG module in Emacs is leaky or it's just a badly coded SVG / scripting (This was using svg-clock.el)

**Comment by mclearc** [comment]
The magit-log thing is weird. Perhaps I introduced some error somewhere in the last couple months. Will try and look over all the code. But thanks very much for these additions and looking forward to seeing that dedicated clock font!

**Comment by jasonm23** [comment]
[fontello-922b3d6a.zip](https://github.com/Lambda-Emacs/lambda-line/files/9592201/fontello-922b3d6a.zip)


Ok attached the first draft of the clock font. Glyphs are named as 00:00..11:55.

**Comment by jasonm23** [comment]
Unicode range starts at `&#x2700;`

**Comment by jasonm23** [comment]
Repo just live now for the font.

https://github.com/ocodo/ClockFace-font

**Comment by jasonm23** [comment]
BTW this is so fresh, I haven't even tried it as a font. Straight from the foundry 💯 

So it may be very shonky.

**Comment by jasonm23** [comment]
So, I'm just quitting for the day.  The plan for the font is:

- Check it's ok, and try it in Emacs
- Make versions:
  - hands cut-out of a circle (so they're transparent, and the circle is solid.
  - very thin/light line for the framing circle.
  - rounded rect frame, a bit like the svg-tags project.
  - a version with different thickness for the hour & minute hand.

We'll see how they work out. Have a good (whatever time of day it is with you.)

**Comment by mclearc** [comment]
Great! -- I'll give it a spin and see how things go. And you as well!

**Pull request merged**
