### PR TITLE
Display time implementation

### PR DESCRIPTION
**Pull request by jasonm23**
A starting point.

### CODE REVIEW

**Comment by jasonm23** [comment]
wrt ce8f184 I'll add on a commit to format the code around these better.

**Comment by jasonm23** [comment]
Ok, I can't test all of these modes / & I wonder how you are testing this?

**Comment by jasonm23** [comment]
NB: Not to be merged as is.

**Comment by mclearc** [comment]
> Ok, I can't test all of these modes / & I wonder how you are testing this?

by someone reporting a bug :).

**Comment by mclearc** [comment]
I like the custom vars, but it would be nice (at least if it's not too much of a PITA) if they were in a separate PR. Otherwise the basic idea seems good. Secondary position seems the best place to put it, though I think a case could be made for tertiary. But I'm happy with either. Let me know if there are rough edges you're concerned about and I can try and take a look later today.

**Comment by jasonm23** [comment]
> ... it would be nice (at least if it's not too much of a PITA) if they were in a separate PR.

That was the plan.  I just wanted to check I was hitting all the right parts of the mode-line.

I _think_ I'm putting them all at the end of _secondary_, that's why I wanted to get your eyes on the code before I tidied up fixed the PR scope(s).

**Comment by jasonm23** [comment]
I'll push a new commit here when the other PR is merged.

**Comment by jasonm23** [comment]
Hi @mclearc can you help me put this in secondary? It doesn't show up so I guess I'm doing something wrong.

**Comment by jasonm23** [comment]
(same goes for trying to put it on the right side, last position. I can only see it when I place it in the current slot.)

**Comment by mclearc** [comment]
> (same goes for trying to put it on the right side, last position. I can only see it when I place it in the current slot.)

Seems to be working on my end. These two both produce expected results.

```emacs-lisp
(defun lambda-line-default-mode ()
  "Compose the default status line."
  (let ((buffer-name (format-mode-line (if buffer-file-name (file-name-nondirectory (buffer-file-name)) "%b")))
        (mode-name   (lambda-line-mode-name))
        (time        (lambda-line-time))
        (branch      (lambda-line-vc-project-branch))
        (position    (format-mode-line "%l:%c:%o")))
    (lambda-line-compose (lambda-line-status)
                         (lambda-line-truncate buffer-name lambda-line-truncate-value)
                         (concat lambda-line-display-group-start mode-name
                                 (when branch
                                   branch)
                                 lambda-line-display-group-end)
                         time
                         ;; Narrowed buffer
                         (if (buffer-narrowed-p)
                             (concat
                              (propertize "⇥ "  'face `(:inherit lambda-line-inactive-secondary))
                              time " " position " ")
                           position))))

(defun lambda-line-prog-mode ()
  (let ((buffer-name (format-mode-line (if buffer-file-name (file-name-nondirectory (buffer-file-name)) "%b")))
        (mode-name   (lambda-line-mode-name))
        (branch      (lambda-line-vc-project-branch))
        (time        (lambda-line-time))
        (position    (format-mode-line "%l:%c:%o")))
    (lambda-line-compose (lambda-line-status)
                         (lambda-line-truncate buffer-name lambda-line-truncate-value)
                         (concat lambda-line-display-group-start mode-name
                                 (when branch branch)
                                 lambda-line-display-group-end)
                         (if lambda-line-syntax
                             (lambda-line-check-syntax) "")
                         (concat
                          ;; Narrowed buffer
                          (when (buffer-narrowed-p)
                            (propertize "⇥ "  'face `(:inherit lambda-line-inactive-secondary)))
                          time
                          (if lambda-line-syntax
                              (if (or (boundp 'flycheck-mode)
                                      (boundp 'flymake-mode))
                                  ;; (concat position lambda-line-hspace)
                                  position)
                            position)))))
```

**Comment by jasonm23** [comment]
I'll give it another go today

**Comment by mclearc** [comment]
> I'll give it another go today

Thanks @jasonm23, let me know if it continues to give you trouble. One thing I've noticed, which has to do with all-the-icons rather than lambda-line, is that I have trouble getting the icon to display properly unless I put `(set-fontset-font t 'unicode (font-spec :family "Weather Icons") nil 'prepend)`. But then this breaks my other icons. Perhaps you can paste your icon config here and I'll add it to the readme?

**Comment by jasonm23** [comment]
Works fine.

I'm refreshing my knowledge re: inserting SVG, so the clock is dynamic and open to customization.

I've had a look at building a clock face font, but the trade-off is poor compared with just doing a SVG clock.

- - -

As an aside, are you open to a code reformat PR?

I use parinfer usually, however, it automatically disables itself when faced with TAB chars in the code.

The  the reformat PR would just be what parinfer does when fixing the code to match it's operation (essentially it augments the parens with pythonic indentation.)

I guess no harm in just sending a PR and you can accept/reject as you see fit.  With the changes visible it's easier to make that choice.

**Comment by mclearc** [comment]
thanks! I'll hopefully be able to review all this later tonight.

**Review by mclearc — APPROVED** [review]

**Pull request merged**
